/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projeto.a3.view;

/**
 *
 * @author pc
 */
public class NoteView extends javax.swing.JPanel {

    /**
     * Creates new form a
     */
    public NoteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JTextField();
        MainPanel = new javax.swing.JScrollPane();
        TextEditor = new javax.swing.JEditorPane();
        SidePanel = new javax.swing.JScrollPane();
        NoteList = new javax.swing.JList<>();
        NewButtom = new javax.swing.JButton();
        DeleteAllButtom = new javax.swing.JButton();
        SaveButton = new javax.swing.JButton();
        ClearButton = new javax.swing.JButton();
        DeleteButtom = new javax.swing.JButton();

        Title.setToolTipText("");
        Title.setEnabled(false);

        MainPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        TextEditor.setEnabled(false);
        MainPanel.setViewportView(TextEditor);

        SidePanel.setViewportView(NoteList);

        NewButtom.setText("Novo");

        DeleteAllButtom.setText("Limpar");
        DeleteAllButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteAllButtomActionPerformed(evt);
            }
        });

        SaveButton.setText("Salvar");
        SaveButton.setEnabled(false);

        ClearButton.setText("Limpar");
        ClearButton.setEnabled(false);

        DeleteButtom.setText("Deletar");
        DeleteButtom.setEnabled(false);
        DeleteButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NewButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DeleteAllButtom))
                    .addComponent(SidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 155, Short.MAX_VALUE)
                        .addComponent(DeleteButtom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClearButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SaveButton))
                    .addComponent(Title)
                    .addComponent(MainPanel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MainPanel))
                    .addComponent(SidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SaveButton)
                    .addComponent(ClearButton)
                    .addComponent(NewButtom)
                    .addComponent(DeleteButtom)
                    .addComponent(DeleteAllButtom))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteAllButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteAllButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteAllButtomActionPerformed

    private void DeleteButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteButtomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteButtomActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearButton;
    private javax.swing.JButton DeleteAllButtom;
    private javax.swing.JButton DeleteButtom;
    private javax.swing.JScrollPane MainPanel;
    private javax.swing.JButton NewButtom;
    private javax.swing.JList<String> NoteList;
    private javax.swing.JButton SaveButton;
    private javax.swing.JScrollPane SidePanel;
    private javax.swing.JEditorPane TextEditor;
    private javax.swing.JTextField Title;
    // End of variables declaration//GEN-END:variables
}
